#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-argparse4j
Version  : 0.7.0
Release  : 1
URL      : https://github.com/argparse4j/argparse4j/archive/argparse4j-0.7.0.tar.gz
Source0  : https://github.com/argparse4j/argparse4j/archive/argparse4j-0.7.0.tar.gz
Source1  : https://repo.maven.apache.org/maven2/net/sourceforge/argparse4j/argparse4j/0.7.0/argparse4j-0.7.0.jar
Source2  : https://repo.maven.apache.org/maven2/net/sourceforge/argparse4j/argparse4j/0.7.0/argparse4j-0.7.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-argparse4j-data = %{version}-%{release}
Requires: mvn-argparse4j-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
Argparse4j - The Java command-line argument parser library
==========================================================

%package data
Summary: data components for the mvn-argparse4j package.
Group: Data

%description data
data components for the mvn-argparse4j package.


%package license
Summary: license components for the mvn-argparse4j package.
Group: Default

%description license
license components for the mvn-argparse4j package.


%prep
%setup -q -n argparse4j-argparse4j-0.7.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-argparse4j
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-argparse4j/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/argparse4j/argparse4j/0.7.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/argparse4j/argparse4j/0.7.0/argparse4j-0.7.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/argparse4j/argparse4j/0.7.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/argparse4j/argparse4j/0.7.0/argparse4j-0.7.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/sourceforge/argparse4j/argparse4j/0.7.0/argparse4j-0.7.0.jar
/usr/share/java/.m2/repository/net/sourceforge/argparse4j/argparse4j/0.7.0/argparse4j-0.7.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-argparse4j/LICENSE.txt
